export const actionTypes = {
  // Auth
  INCREASE_STUDENT_COUNT: 'INCREASE_STUDENT_COUNT',
  DECREASE_STUDENT_COUNT: 'DECREASE_STUDENT_COUNT',
  INCREASE_BUS_COUNT: 'INCREASE_BUS_COUNT',
  DECREASE_BUS_COUNT: 'DECREASE_BUS_COUNT',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  SIGNUP_OTP: 'SIGNUP_OTP',
  SIGNUP_PASSWORD: 'SIGNUP_PASSWORD',
  LOGOUT: 'LOGOUT',
  GET_ME: 'GET_ME',
  TOKEN: 'TOKEN',
  SIGNUPEMAILDATA: 'SIGNUPEMAILDATA',
  FORGET_NEW_PASSWORD: 'FORGET_NEW_PASSWORD',
  UPDATE_NEW_PASSWORD: 'UPDATE_NEW_PASSWORD',
  INCREASE_SLOTS: 'INCREASE_SLOTS',
  DECREASE_SLOTS: 'DECREASE_SLOTS',
  UPDATE_EMAIL_OTP: 'UPDATE_EMAIL_OTP',
  UPDATE_DATA: 'UPDATE_DATA',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  SET_PROFILE_INFO: 'SET_PROFILE_INFO',
  UPDATE_EMAIL_DATA: 'UPDATE_EMAIL_DATA',
  GET_TOTAL_COUNT_OF_COLLECTIONS:'GET_TOTAL_COUNT_OF_COLLECTIONS',

  //   FORGOT_PASSWORD: "FORGOT_PASSWORD",
  SET_WAREHOUSE_ADDRESS: 'SET_WAREHOUSE_ADDRESS',
  GET_LISTING_REQUEST_ORDERS: 'GET_LISTING_REQUEST_ORDERS',

  // Bus
  ADD_BUS: 'ADD_BUS',
  ADD_MULTIPLE_BUSES: 'ADD_MULTIPLE_BUSES',
  FETCH_ALL_BUSES: 'FETCH_ALL_BUSES',
  FETCH_UNASSIGNED_BUSES: 'FETCH_UNASSIGNED_BUSES',
  FETCH_SINGLE_BUS: 'FETCH_SINGLE_BUS',
  DELETE_BUS: 'DELETE_BUS',
  REMOVE_BUS: 'REMOVE_BUS',
  ASSIGN_STUDENT: 'ASSIGN_STUDENT',
  UNASSIGN_STUDENT: 'UNASSIGN_STUDENT',
  FETCH_BUS_STUDENTS: 'FETCH_BUS_STUDENTS',
  FETCH_UNASSIGNED_STUDENTS: 'FETCH_UNASSIGNED_STUDENTS',
  EDIT_BUS: 'EDIT_BUS',

  // Route
  ADD_ROUTE: 'ADD_ROUTE',
  FETCH_ALL_ROUTES: 'FETCH_ALL_ROUTES',
  DELETE_ROUTE: 'DELETE_ROUTE',
  REMOVE_ROUTE: 'REMOVE_ROUTE',
  EDIT_ROUTE: 'EDIT_ROUTE',

  // Static Messages
  ADD_STATIC_MESSAGE: 'ADD_STATIC_MESSAGE',
  FETCH_ALL_STATIC_MESSAGES: 'FETCH_ALL_STATIC_MESSAGES',
  DELETE_STATIC_MESSAGE: 'DELETE_STATIC_MESSAGE',
  REMOVE_STATIC_MESSAGE: 'REMOVE_STATIC_MESSAGE',
  EDIT_STATIC_MESSAGE: 'EDIT_STATIC_MESSAGE',

  // Driver
  ADD_DRIVER: 'ADD_DRIVER',
  ADD_MULTIPLE_DRIVERS: 'ADD_MULTIPLE_DRIVERS',
  FETCH_ALL_DRIVERS: 'FETCH_ALL_DRIVERS',
  FETCH_UNASSIGNED_DRIVERS: 'FETCH_UNASSIGNED_DRIVERS',
  FETCH_DRIVER_HISTORY: 'FETCH_DRIVER_HISTORY',
  DELETE_DRIVER: 'DELETE_DRIVER',
  REMOVE_DRIVER: 'REMOVE_DRIVER',
  EDIT_DRIVER: 'EDIT_DRIVER',

  // Parent
  ADD_PARENT: 'ADD_PARENT',
  ADD_MULTIPLE_PARENTS: 'ADD_MULTIPLE_PARENTS',
  FETCH_ALL_PARENTS: 'FETCH_ALL_PARENTS',
  FETCH_PARENT_CHILDREN: 'FETCH_PARENT_CHILDREN',
  DELETE_PARENT: 'DELETE_PARENT',
  REMOVE_PARENT: 'REMOVE_PARENT',
  REVOKE_REGISTERATION: 'REVOKE_REGISTERATION',
  EDIT_PARENT: 'EDIT_PARENT',

  // School
  ADD_SCHOOL: 'ADD_SCHOOL',
  FETCH_ALL_PACKAGES: 'FETCH_ALL_PACKAGES',
  EDIT_SCHOOL: 'EDIT_SCHOOL',
  UPDATE_SCHOOL: 'UPDATE_SCHOOL',

  // Student
  ADD_STUDENT: 'ADD_STUDENT',
  ADD_MULTIPLE_STUDENTS: 'ADD_MULTIPLE_STUDENTS',
  FETCH_ALL_STUDENTS: 'FETCH_ALL_STUDENTS',
  DELETE_STUDENT: 'DELETE_STUDENT',
  REMOVE_STUDENT: 'REMOVE_STUDENT',
  SET_STUDENT_IMAGE: 'SET_STUDENT_IMAGE',
  SET_MULTIPLE_STUDENT_IMAGE: 'SET_MULTIPLE_STUDENT_IMAGE',
  EDIT_STUDENT: 'EDIT_STUDENT',
  FETCH_STUDENT_HISTORY: 'FETCH_STUDENT_HISTORY',

  //Billing
  FETCH_BILLING_HISTORY: 'FETCH_BILLING_HISTORY',

  // // Product
  // ADD_PRODUCT: "ADD_PRODUCT",
  // GET_GENERAL_ARTS: "GET_GENERAL_ARTS",
  // GET_AUCTION_ARTS: "GET_AUCTION_ARTS",
  // GET_MASTERPIECE_ARTS: "GET_MASTERPIECE_ARTS",
  // GET_ALL_ARTS: "GET_ALL_ARTS",
  // VIEW_ART: "VIEW_ART",
  // GET_VENDORS_PRODUCTS_BY_CATEGORIES: "GET_VENDORS_PRODUCTS_BY_CATEGORIES",
  // ENABLE_DISABLE_PRODUCT: "ENABLE_DISABLE_PRODUCT",
  // DELETE_PRODUCT: "DELETE_PRODUCT",
  // EDIT_PRODUCT: "EDIT_PRODUCT",
  // GET_ALL_PRODUCTS_LIST_FOT_SEARCH: "GET_ALL_PRODUCTS_LIST_FOT_SEARCH",
  // GET_PRODUCT_DETAILS_BY_ID: "GET_PRODUCT_DETAILS_BY_ID",
  // GET_RESERVE_ARTS: "GET_RESERVE_ARTS",
  // GET_TRADES: "GET_TRADES",
  // DELETE_ART: "DELETE_ART",
  // DELETE_AUCTION: "DELETE_AUCTION",
  // UPDATE_ART: "UPDATE_ART",
  // UPDATE_AUCTION_ART: "UPDATE_AUCTION_ART",
  // GET_LISTING_APPROVED_ORDERS: "GET_LISTING_APPROVED_ORDERS",

  // // orders
  // GET_ALL_ORDERS: "GET_ALL_ORDERS",
  // GET_PENDING_ORDERS: "GET_PENDING_ORDERS",
  // GET_PORTRAIT_REQUEST_ORDERS: "GET_PORTRAIT_REQUEST_ORDERS",

  // //dashboard
  // GET_DASHBOARD_ORDERS: "GET_DASHBOARD_ORDERS",

  // GET_PORTRAIT_ORDERS: "GET_PORTRAIT_ORDERS",

  // SUCCESS: "SUCCESS",

  // //notification
  // GET_NOTIFICATION: "GET_NOTIFICATION",
  // //Artist request
  // GET_ARTIST_REQUEST: "GET_ARTIST_REQUEST",
  // GET_ARTIST: "GET_ARTIST",
  // APPROVED_ARTIST: "APPROVED_ARTIST",

  // //finance
  // GET_TRANSACTION_OVERVIEW: "GET_TRANSACTION_OVERVIEW",

  // //charges
  // GET_CHARGES: "GET_CHARGES",
  // SET_CHARGES: "SET_CHARGES",
};
